version: 2

jobs:
  build:
    working_directory: ~/mocha-suite
    docker:
      - image: kkarczmarczyk/node-yarn
    steps:
      - checkout
      - restore_cache:
          key: mocha-suite-{{ .Branch }}-{{ checksum "package.json" "yarn.lock" }}
      - run:
          name: Install
          command: yarn
      - save_cache:
          key: mocha-suite-{{ .Branch }}-{{ checksum "package.json" "yarn.lock" }}
          paths:
            - "~/node_modules"
      - run:
          name: Test
          command: yarn start ci
      - run:
          name: Release
          command: yarn start release
